//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package fr.progilone.pgcn.domain.jaxb.aip;

import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import java.time.LocalDateTime;

/**
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;description xmlns:ISO-639-3="urn:un:unece:uncefact:codelist:draft:DAF:languageCode:2011-10-07" xmlns:RA="urn:un:unece:uncefact:codelist:draft:DAF:accessRestrictionCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;pour les archives intermédiaires, permet d'indiquer la durée d'utilité administrative du document et le traitement à appliquer à l'issue de cette durée&lt;/description&gt;
 * </pre>
 *
 *
 *
 * <p>
 * Java class for evaluationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class.
 *
 * <pre>
 * &lt;complexType name="evaluationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}DUA"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}traitement"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}dateDebut"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "evaluationType", propOrder = { "dua", "traitement", "dateDebut" })
public class EvaluationType {

	@XmlElement(name = "DUA", required = true)
	protected Duration dua;

	@XmlElement(required = true)
	protected TraitementType traitement;

	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected LocalDateTime dateDebut;

	/**
	 * Gets the value of the dua property.
	 * @return possible object is {@link Duration }
	 *
	 */
	public Duration getDUA() {
		return dua;
	}

	/**
	 * Sets the value of the dua property.
	 * @param value allowed object is {@link Duration }
	 *
	 */
	public void setDUA(Duration value) {
		this.dua = value;
	}

	/**
	 * Gets the value of the traitement property.
	 * @return possible object is {@link TraitementType }
	 *
	 */
	public TraitementType getTraitement() {
		return traitement;
	}

	/**
	 * Sets the value of the traitement property.
	 * @param value allowed object is {@link TraitementType }
	 *
	 */
	public void setTraitement(TraitementType value) {
		this.traitement = value;
	}

	/**
	 * Gets the value of the dateDebut property.
	 * @return possible object is {@link LocalDateTime }
	 *
	 */
	public LocalDateTime getDateDebut() {
		return dateDebut;
	}

	/**
	 * Sets the value of the dateDebut property.
	 * @param value allowed object is {@link LocalDateTime }
	 *
	 */
	public void setDateDebut(LocalDateTime value) {
		this.dateDebut = value;
	}

}
