//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//


package fr.progilone.pgcn.domain.jaxb.aip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Métadonnées des
 * 				fichiers composant le document
 *
 * <p>Java class for FichMetaType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FichMetaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}idFichier" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}nomFichier"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}compression" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}encodage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}formatFichier"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}noteFichier" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}structureFichier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}versionFormatFichier" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}empreinte"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}empreinteOri" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}idDocument" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}migration" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}tailleEnOctets"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FichMetaType", propOrder = {
    "idFichier",
    "nomFichier",
    "compression",
    "encodage",
    "formatFichier",
    "noteFichier",
    "structureFichier",
    "versionFormatFichier",
    "empreinte",
    "empreinteOri",
    "idDocument",
    "migration",
    "tailleEnOctets"
})
public class FichMetaType {

    protected String idFichier;
    @XmlElement(required = true)
    protected String nomFichier;
    protected String compression;
    protected String encodage;
    @XmlElement(required = true)
    protected String formatFichier;
    protected StringNotNULLtext noteFichier;
    protected List<StructureFichier> structureFichier;
    protected String versionFormatFichier;
    @XmlElement(required = true)
    protected EmpreinteType empreinte;
    protected EmpreinteOri empreinteOri;
    protected String idDocument;
    protected String migration;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger tailleEnOctets;

    /**
     * Gets the value of the idFichier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdFichier() {
        return idFichier;
    }

    /**
     * Sets the value of the idFichier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdFichier(String value) {
        this.idFichier = value;
    }

    /**
     * Gets the value of the nomFichier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomFichier() {
        return nomFichier;
    }

    /**
     * Sets the value of the nomFichier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomFichier(String value) {
        this.nomFichier = value;
    }

    /**
     * Gets the value of the compression property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCompression(String value) {
        this.compression = value;
    }

    /**
     * Gets the value of the encodage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEncodage() {
        return encodage;
    }

    /**
     * Sets the value of the encodage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEncodage(String value) {
        this.encodage = value;
    }

    /**
     * Gets the value of the formatFichier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFormatFichier() {
        return formatFichier;
    }

    /**
     * Sets the value of the formatFichier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFormatFichier(String value) {
        this.formatFichier = value;
    }

    /**
     * Gets the value of the noteFichier property.
     *
     * @return
     *     possible object is
     *     {@link StringNotNULLtext }
     *
     */
    public StringNotNULLtext getNoteFichier() {
        return noteFichier;
    }

    /**
     * Sets the value of the noteFichier property.
     *
     * @param value
     *     allowed object is
     *     {@link StringNotNULLtext }
     *
     */
    public void setNoteFichier(StringNotNULLtext value) {
        this.noteFichier = value;
    }

    /**
     * Gets the value of the structureFichier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the structureFichier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStructureFichier().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StructureFichier }
     *
     *
     */
    public List<StructureFichier> getStructureFichier() {
        if (structureFichier == null) {
            structureFichier = new ArrayList<StructureFichier>();
        }
        return this.structureFichier;
    }

    /**
     * Gets the value of the versionFormatFichier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersionFormatFichier() {
        return versionFormatFichier;
    }

    /**
     * Sets the value of the versionFormatFichier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersionFormatFichier(String value) {
        this.versionFormatFichier = value;
    }

    /**
     * Gets the value of the empreinte property.
     *
     * @return
     *     possible object is
     *     {@link EmpreinteType }
     *
     */
    public EmpreinteType getEmpreinte() {
        return empreinte;
    }

    /**
     * Sets the value of the empreinte property.
     *
     * @param value
     *     allowed object is
     *     {@link EmpreinteType }
     *
     */
    public void setEmpreinte(EmpreinteType value) {
        this.empreinte = value;
    }

    /**
     * Gets the value of the empreinteOri property.
     *
     * @return
     *     possible object is
     *     {@link EmpreinteOri }
     *
     */
    public EmpreinteOri getEmpreinteOri() {
        return empreinteOri;
    }

    /**
     * Sets the value of the empreinteOri property.
     *
     * @param value
     *     allowed object is
     *     {@link EmpreinteOri }
     *
     */
    public void setEmpreinteOri(EmpreinteOri value) {
        this.empreinteOri = value;
    }

    /**
     * Gets the value of the idDocument property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdDocument() {
        return idDocument;
    }

    /**
     * Sets the value of the idDocument property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdDocument(String value) {
        this.idDocument = value;
    }

    /**
     * Gets the value of the migration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMigration() {
        return migration;
    }

    /**
     * Sets the value of the migration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMigration(String value) {
        this.migration = value;
    }

    /**
     * Gets the value of the tailleEnOctets property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getTailleEnOctets() {
        return tailleEnOctets;
    }

    /**
     * Sets the value of the tailleEnOctets property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setTailleEnOctets(BigInteger value) {
        this.tailleEnOctets = value;
    }

}
