//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//


package fr.progilone.pgcn.domain.jaxb.aip;

import java.math.BigInteger;
import javax.xml.datatype.Duration;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.time.LocalDateTime;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the fr.cines.pac.aip package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Title_QNAME = new QName("http://www.cines.fr/pac/aip", "title");
    private final static QName _Creator_QNAME = new QName("http://www.cines.fr/pac/aip", "creator");
    private final static QName _Subject_QNAME = new QName("http://www.cines.fr/pac/aip", "subject");
    private final static QName _Description_QNAME = new QName("http://www.cines.fr/pac/aip", "description");
    private final static QName _Publisher_QNAME = new QName("http://www.cines.fr/pac/aip", "publisher");
    private final static QName _Contributor_QNAME = new QName("http://www.cines.fr/pac/aip", "contributor");
    private final static QName _Date_QNAME = new QName("http://www.cines.fr/pac/aip", "date");
    private final static QName _Type_QNAME = new QName("http://www.cines.fr/pac/aip", "type");
    private final static QName _Format_QNAME = new QName("http://www.cines.fr/pac/aip", "format");
    private final static QName _Source_QNAME = new QName("http://www.cines.fr/pac/aip", "source");
    private final static QName _Language_QNAME = new QName("http://www.cines.fr/pac/aip", "language");
    private final static QName _Relation_QNAME = new QName("http://www.cines.fr/pac/aip", "relation");
    private final static QName _Coverage_QNAME = new QName("http://www.cines.fr/pac/aip", "coverage");
    private final static QName _Rights_QNAME = new QName("http://www.cines.fr/pac/aip", "rights");
    private final static QName _IdentifiantDocProducteur_QNAME = new QName("http://www.cines.fr/pac/aip", "identifiantDocProducteur");
    private final static QName _DocRelation_QNAME = new QName("http://www.cines.fr/pac/aip", "docRelation");
    private final static QName _TypeRelation_QNAME = new QName("http://www.cines.fr/pac/aip", "typeRelation");
    private final static QName _SourceRelation_QNAME = new QName("http://www.cines.fr/pac/aip", "sourceRelation");
    private final static QName _IdentifiantSourceRelation_QNAME = new QName("http://www.cines.fr/pac/aip", "identifiantSourceRelation");
    private final static QName _Evaluation_QNAME = new QName("http://www.cines.fr/pac/aip", "evaluation");
    private final static QName _DUA_QNAME = new QName("http://www.cines.fr/pac/aip", "DUA");
    private final static QName _Traitement_QNAME = new QName("http://www.cines.fr/pac/aip", "traitement");
    private final static QName _DateDebut_QNAME = new QName("http://www.cines.fr/pac/aip", "dateDebut");
    private final static QName _Communicabilite_QNAME = new QName("http://www.cines.fr/pac/aip", "communicabilite");
    private final static QName _Code_QNAME = new QName("http://www.cines.fr/pac/aip", "code");
    private final static QName _NoteDocument_QNAME = new QName("http://www.cines.fr/pac/aip", "noteDocument");
    private final static QName _ServiceVersant_QNAME = new QName("http://www.cines.fr/pac/aip", "serviceVersant");
    private final static QName _PlanClassement_QNAME = new QName("http://www.cines.fr/pac/aip", "planClassement");
    private final static QName _StructureDocument_QNAME = new QName("http://www.cines.fr/pac/aip", "structureDocument");
    private final static QName _Version_QNAME = new QName("http://www.cines.fr/pac/aip", "version");
    private final static QName _VersionPrecedente_QNAME = new QName("http://www.cines.fr/pac/aip", "versionPrecedente");
    private final static QName _Compression_QNAME = new QName("http://www.cines.fr/pac/aip", "compression");
    private final static QName _Encodage_QNAME = new QName("http://www.cines.fr/pac/aip", "encodage");
    private final static QName _FormatFichier_QNAME = new QName("http://www.cines.fr/pac/aip", "formatFichier");
    private final static QName _NomFichier_QNAME = new QName("http://www.cines.fr/pac/aip", "nomFichier");
    private final static QName _NoteFichier_QNAME = new QName("http://www.cines.fr/pac/aip", "noteFichier");
    private final static QName _Pac_QNAME = new QName("http://www.cines.fr/pac/aip", "pac");
    private final static QName _DocDC_QNAME = new QName("http://www.cines.fr/pac/aip", "DocDC");
    private final static QName _Identifier_QNAME = new QName("http://www.cines.fr/pac/aip", "identifier");
    private final static QName _DocMeta_QNAME = new QName("http://www.cines.fr/pac/aip", "DocMeta");
    private final static QName _Authenticite_QNAME = new QName("http://www.cines.fr/pac/aip", "authenticite");
    private final static QName _DateArchivage_QNAME = new QName("http://www.cines.fr/pac/aip", "dateArchivage");
    private final static QName _DureeConservation_QNAME = new QName("http://www.cines.fr/pac/aip", "dureeConservation");
    private final static QName _IdentifiantDocPac_QNAME = new QName("http://www.cines.fr/pac/aip", "identifiantDocPac");
    private final static QName _IdentifiantVersement_QNAME = new QName("http://www.cines.fr/pac/aip", "identifiantVersement");
    private final static QName _Projet_QNAME = new QName("http://www.cines.fr/pac/aip", "projet");
    private final static QName _SortFinal_QNAME = new QName("http://www.cines.fr/pac/aip", "sortFinal");
    private final static QName _FichMeta_QNAME = new QName("http://www.cines.fr/pac/aip", "FichMeta");
    private final static QName _IdFichier_QNAME = new QName("http://www.cines.fr/pac/aip", "idFichier");
    private final static QName _VersionFormatFichier_QNAME = new QName("http://www.cines.fr/pac/aip", "versionFormatFichier");
    private final static QName _Empreinte_QNAME = new QName("http://www.cines.fr/pac/aip", "empreinte");
    private final static QName _IdDocument_QNAME = new QName("http://www.cines.fr/pac/aip", "idDocument");
    private final static QName _Migration_QNAME = new QName("http://www.cines.fr/pac/aip", "migration");
    private final static QName _TailleEnOctets_QNAME = new QName("http://www.cines.fr/pac/aip", "tailleEnOctets");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.cines.pac.aip
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StringNotNULLtext }
     *
     */
    public StringNotNULLtext createStringNotNULLtext() {
        return new StringNotNULLtext();
    }

    /**
     * Create an instance of {@link DocRelationType }
     *
     */
    public DocRelationType createDocRelationType() {
        return new DocRelationType();
    }

    /**
     * Create an instance of {@link EvaluationType }
     *
     */
    public EvaluationType createEvaluationType() {
        return new EvaluationType();
    }

    /**
     * Create an instance of {@link TraitementType }
     *
     */
    public TraitementType createTraitementType() {
        return new TraitementType();
    }

    /**
     * Create an instance of {@link CommunicabiliteType }
     *
     */
    public CommunicabiliteType createCommunicabiliteType() {
        return new CommunicabiliteType();
    }

    /**
     * Create an instance of {@link CodeType }
     *
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link EmpreinteOri }
     *
     */
    public EmpreinteOri createEmpreinteOri() {
        return new EmpreinteOri();
    }

    /**
     * Create an instance of {@link StructureFichier }
     *
     */
    public StructureFichier createStructureFichier() {
        return new StructureFichier();
    }

    /**
     * Create an instance of {@link PacType }
     *
     */
    public PacType createPacType() {
        return new PacType();
    }

    /**
     * Create an instance of {@link DocDCType }
     *
     */
    public DocDCType createDocDCType() {
        return new DocDCType();
    }

    /**
     * Create an instance of {@link DocMetaType }
     *
     */
    public DocMetaType createDocMetaType() {
        return new DocMetaType();
    }

    /**
     * Create an instance of {@link FichMetaType }
     *
     */
    public FichMetaType createFichMetaType() {
        return new FichMetaType();
    }

    /**
     * Create an instance of {@link EmpreinteType }
     *
     */
    public EmpreinteType createEmpreinteType() {
        return new EmpreinteType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "title")
    public JAXBElement<StringNotNULLtext> createTitle(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Title_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "creator")
    public JAXBElement<String> createCreator(String value) {
        return new JAXBElement<String>(_Creator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "subject")
    public JAXBElement<StringNotNULLtext> createSubject(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Subject_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "description")
    public JAXBElement<StringNotNULLtext> createDescription(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Description_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "publisher")
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<String>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "contributor")
    public JAXBElement<String> createContributor(String value) {
        return new JAXBElement<String>(_Contributor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "type")
    public JAXBElement<StringNotNULLtext> createType(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Type_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "format")
    public JAXBElement<StringNotNULLtext> createFormat(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Format_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "source")
    public JAXBElement<StringNotNULLtext> createSource(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Source_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "relation")
    public JAXBElement<StringNotNULLtext> createRelation(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Relation_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "coverage")
    public JAXBElement<StringNotNULLtext> createCoverage(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Coverage_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "rights")
    public JAXBElement<StringNotNULLtext> createRights(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_Rights_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "identifiantDocProducteur")
    public JAXBElement<String> createIdentifiantDocProducteur(String value) {
        return new JAXBElement<String>(_IdentifiantDocProducteur_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocRelationType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DocRelationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "docRelation")
    public JAXBElement<DocRelationType> createDocRelation(DocRelationType value) {
        return new JAXBElement<DocRelationType>(_DocRelation_QNAME, DocRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "typeRelation")
    public JAXBElement<String> createTypeRelation(String value) {
        return new JAXBElement<String>(_TypeRelation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "sourceRelation")
    public JAXBElement<String> createSourceRelation(String value) {
        return new JAXBElement<String>(_SourceRelation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "identifiantSourceRelation")
    public JAXBElement<String> createIdentifiantSourceRelation(String value) {
        return new JAXBElement<String>(_IdentifiantSourceRelation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EvaluationType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EvaluationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "evaluation")
    public JAXBElement<EvaluationType> createEvaluation(EvaluationType value) {
        return new JAXBElement<EvaluationType>(_Evaluation_QNAME, EvaluationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "DUA")
    public JAXBElement<Duration> createDUA(Duration value) {
        return new JAXBElement<Duration>(_DUA_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitementType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TraitementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "traitement")
    public JAXBElement<TraitementType> createTraitement(TraitementType value) {
        return new JAXBElement<TraitementType>(_Traitement_QNAME, TraitementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalDateTime }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LocalDateTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "dateDebut")
    public JAXBElement<LocalDateTime> createDateDebut(LocalDateTime value) {
        return new JAXBElement<LocalDateTime>(_DateDebut_QNAME, LocalDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicabiliteType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommunicabiliteType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "communicabilite")
    public JAXBElement<CommunicabiliteType> createCommunicabilite(CommunicabiliteType value) {
        return new JAXBElement<CommunicabiliteType>(_Communicabilite_QNAME, CommunicabiliteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "code")
    public JAXBElement<CodeType> createCode(CodeType value) {
        return new JAXBElement<CodeType>(_Code_QNAME, CodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "noteDocument")
    public JAXBElement<StringNotNULLtext> createNoteDocument(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_NoteDocument_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "serviceVersant")
    public JAXBElement<String> createServiceVersant(String value) {
        return new JAXBElement<String>(_ServiceVersant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "planClassement")
    public JAXBElement<StringNotNULLtext> createPlanClassement(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_PlanClassement_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "structureDocument")
    public JAXBElement<String> createStructureDocument(String value) {
        return new JAXBElement<String>(_StructureDocument_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "versionPrecedente")
    public JAXBElement<String> createVersionPrecedente(String value) {
        return new JAXBElement<String>(_VersionPrecedente_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "compression")
    public JAXBElement<String> createCompression(String value) {
        return new JAXBElement<String>(_Compression_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "encodage")
    public JAXBElement<String> createEncodage(String value) {
        return new JAXBElement<String>(_Encodage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "formatFichier")
    public JAXBElement<String> createFormatFichier(String value) {
        return new JAXBElement<String>(_FormatFichier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "nomFichier")
    public JAXBElement<String> createNomFichier(String value) {
        return new JAXBElement<String>(_NomFichier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "noteFichier")
    public JAXBElement<StringNotNULLtext> createNoteFichier(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_NoteFichier_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PacType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PacType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "pac")
    public JAXBElement<PacType> createPac(PacType value) {
        return new JAXBElement<PacType>(_Pac_QNAME, PacType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocDCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DocDCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "DocDC")
    public JAXBElement<DocDCType> createDocDC(DocDCType value) {
        return new JAXBElement<DocDCType>(_DocDC_QNAME, DocDCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "identifier")
    public JAXBElement<String> createIdentifier(String value) {
        return new JAXBElement<String>(_Identifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocMetaType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DocMetaType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "DocMeta")
    public JAXBElement<DocMetaType> createDocMeta(DocMetaType value) {
        return new JAXBElement<DocMetaType>(_DocMeta_QNAME, DocMetaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "authenticite")
    public JAXBElement<String> createAuthenticite(String value) {
        return new JAXBElement<String>(_Authenticite_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "dateArchivage")
    public JAXBElement<String> createDateArchivage(String value) {
        return new JAXBElement<String>(_DateArchivage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "dureeConservation")
    public JAXBElement<Duration> createDureeConservation(Duration value) {
        return new JAXBElement<Duration>(_DureeConservation_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "identifiantDocPac")
    public JAXBElement<String> createIdentifiantDocPac(String value) {
        return new JAXBElement<String>(_IdentifiantDocPac_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "identifiantVersement")
    public JAXBElement<String> createIdentifiantVersement(String value) {
        return new JAXBElement<String>(_IdentifiantVersement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "projet")
    public JAXBElement<String> createProjet(String value) {
        return new JAXBElement<String>(_Projet_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringNotNULLtext }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "sortFinal")
    public JAXBElement<StringNotNULLtext> createSortFinal(StringNotNULLtext value) {
        return new JAXBElement<StringNotNULLtext>(_SortFinal_QNAME, StringNotNULLtext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FichMetaType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FichMetaType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "FichMeta")
    public JAXBElement<FichMetaType> createFichMeta(FichMetaType value) {
        return new JAXBElement<FichMetaType>(_FichMeta_QNAME, FichMetaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "idFichier")
    public JAXBElement<String> createIdFichier(String value) {
        return new JAXBElement<String>(_IdFichier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "versionFormatFichier")
    public JAXBElement<String> createVersionFormatFichier(String value) {
        return new JAXBElement<String>(_VersionFormatFichier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmpreinteType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EmpreinteType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "empreinte")
    public JAXBElement<EmpreinteType> createEmpreinte(EmpreinteType value) {
        return new JAXBElement<EmpreinteType>(_Empreinte_QNAME, EmpreinteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "idDocument")
    public JAXBElement<String> createIdDocument(String value) {
        return new JAXBElement<String>(_IdDocument_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "migration")
    public JAXBElement<String> createMigration(String value) {
        return new JAXBElement<String>(_Migration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cines.fr/pac/aip", name = "tailleEnOctets")
    public JAXBElement<BigInteger> createTailleEnOctets(BigInteger value) {
        return new JAXBElement<BigInteger>(_TailleEnOctets_QNAME, BigInteger.class, null, value);
    }

}
