//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package fr.progilone.pgcn.domain.jaxb.aip;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for traitementEnum.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class. <pre>
 * &lt;simpleType name="traitementEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="conservation définitive"/&gt;
 *     &lt;enumeration value="élimination"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "traitementEnum")
@XmlEnum
public enum TraitementEnum {

	@XmlEnumValue("conservation d\u00e9finitive")
	CONSERVATION_DÉFINITIVE("conservation d\u00e9finitive"), @XmlEnumValue("\u00e9limination")
	ÉLIMINATION("\u00e9limination");

	private final String value;

	TraitementEnum(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static TraitementEnum fromValue(String v) {
		for (TraitementEnum c : TraitementEnum.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
