openapi: 3.1.1

info:
  title: NumaHOP Rest API
  description: Specification for the Api of All NumaHOP Applications.
  contact:
    name: NumaHOP users association
    email: association-numahop@sorbonne-nouvelle.fr
    url: https://www.numahop.fr/
  version: 0.0.1

servers:
  - url: /api/rest/v2

tags:
  - name: doc_unit

paths:
  /doc_units:
    description: Document Unit API module.

    get:
      description: Retrives a list of document units.
      operationId: searchDocUnits
      tags:
        - doc_unit
      parameters:
        - name: search
          schema:
            type: string
          in: query
        - name: hasDigitalDocuments
          schema:
            type: boolean
          in: query
        - name: active
          schema:
            type: boolean
          in: query
        - name: archived
          schema:
            type: boolean
          in: query
        - name: achivable
          schema:
            type: boolean
          in: query
        - name: distributed
          schema:
            type: boolean
          in: query
        - name: distribuable
          schema:
            type: boolean
          in: query
        - name: libaries
          schema:
            type: array
            items:
              type: string
          in: query
        - name: projects
          schema:
            type: array
            items:
              type: string
          in: query
        - name: lots
          schema:
            type: array
            items:
              type: string
          in: query
        - name: statuses
          schema:
            type: array
            items:
              $ref: "#/components/schemas/DocUnitState"
          in: query
        - name: lastModifiedDateFrom
          schema:
            type: string
            format: date
          in: query
        - name: lastModifiedDateTo
          schema:
            type: string
            format: date
          in: query
        - name: createdDateFrom
          schema:
            type: string
            fromat: date
          in: query
        - name: createdDateTo
          schema:
            type: string
            format: date
          in: query
        - name: page
          schema:
            type: integer
          in: query
        - name: size
          schema:
            type: integer
          in: query
        - name: sorts
          schema:
            type: array
            items:
              type: string
          in: query

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocUnit"
        "401":
          description: UNAUTHORIZED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "403":
          description: FORBIDEN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"

    post:
      description: Create a document unit.
      operationId: createDocUnit
      tags:
        - doc_unit
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDocUnit"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocUnit"
        "400":
          description: BAD_REQUEST
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "401":
          description: UNAUTHORIZED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "403":
          description: FORBIDEN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"

  /doc_units/{identifier}:
    description: Operations on an existing document unit.

    get:
      description: Retrives a document unit by its identifier.
      operationId: getDocUnitById
      tags:
        - doc_unit
      parameters:
        - name: identifier
          required: true
          schema:
            type: string
          in: path
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocUnit"
        "401":
          description: UNAUTHORIZED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "403":
          description: FORBIDEN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"

    put:
      description: Updates a document unit.
      operationId: updateDocUnit
      tags:
        - doc_unit
      parameters:
        - name: identifier
          required: true
          schema:
            type: string
          in: path
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocUnit"
        "401":
          description: UNAUTHORIZED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "403":
          description: FORBIDEN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"

    delete:
      description: Delete a document unit.
      operationId: deleteDocUnit
      tags:
        - doc_unit
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: OK
        "401":
          description: UNAUTHORIZED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "403":
          description: FORBIDEN
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"

components:
  schemas:
    Errors:
      type: array
      items:
        type: object
        properties:
          error_code:
            type: string

    ObjectWithId:
      type: object
      required:
        - identifier
      properties:
        identifier:
          type: string
        modifiedBy:
          type: string
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date
        createdAt:
          type: string
          format: date

    CreateDocUnit:
      type: object
      required:
        - label
        - pgcn_id
        - rights
        - library
      properties:
        pgcn_id:
          type: string
        label:
          type: string
        library:
          type: string
        type:
          type: string
        rights:
          $ref: "#/components/schemas/DocUnitRights"
        parent:
          type: string
        project_identifier:
          type: string
        lot_identifier:
          type: string
        train_identifier:
          type: string

    DocUnit:
      allOf:
        - $ref: "#/components/schemas/ObjectWithId"
        - $ref: "#/components/schemas/CreateDocUnit"
        - type: object
          properties:
            state:
              $ref: "#/components/schemas/DocUnitState"
            exportStatus:
              $ref: "#/components/schemas/DocUnitExportStatus"
            exportDate:
              type: string
              format: date
            omekaExportStatus:
              $ref: "#/components/schemas/DocUnitExportStatus"
            omekaExportDate:
              type: string
              format: date
            digLibExportStatus:
              $ref: "#/components/schemas/DocUnitExportStatus"
            condReportType:
              $ref: "#/components/schemas/CondReportType"

    DocUnitState:
      type: string
      enum: ["AVAILABLE","NOT_AVAILABLE","DELETED","CANCELED","CLOSED"]

    DocUnitExportStatus:
      type: string
      enum: ["NONE", "IN_PROGRESS", "SENT", "FAILED"]

    DocUnitRights:
      type: string
      enum: ["TO_CHECK", "FREE", "RESTRICTED", "RESTRICTED_WITH_AUTHORIZATION"]

    CondReportType:
      type: string
      enum: ["MONO_PAGE", "MULTI_PAGE"]
