//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package org.numahop.numahop.domain.jaxb.aip;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import java.time.LocalDateTime;

/**
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;description xmlns:ISO-639-3="urn:un:unece:uncefact:codelist:draft:DAF:languageCode:2011-10-07" xmlns:RA="urn:un:unece:uncefact:codelist:draft:DAF:accessRestrictionCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;pour les archives publiques, précise si le document est librement communicable ou soumis à un délai (cf. régime de communication prévu par le Code du Patrimoine, art. L213-1 à L213-8)&lt;/description&gt;
 * </pre>
 *
 *
 *
 * <p>
 * Java class for communicabiliteType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class.
 *
 * <pre>
 * &lt;complexType name="communicabiliteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}code"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}dateDebut"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "communicabiliteType", propOrder = { "code", "dateDebut" })
public class CommunicabiliteType {

	@XmlElement(required = true)
	protected CodeType code;

	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected LocalDateTime dateDebut;

	/**
	 * Gets the value of the code property.
	 * @return possible object is {@link CodeType }
	 *
	 */
	public CodeType getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * @param value allowed object is {@link CodeType }
	 *
	 */
	public void setCode(CodeType value) {
		this.code = value;
	}

	/**
	 * Gets the value of the dateDebut property.
	 * @return possible object is {@link LocalDateTime }
	 *
	 */
	public LocalDateTime getDateDebut() {
		return dateDebut;
	}

	/**
	 * Sets the value of the dateDebut property.
	 * @param value allowed object is {@link LocalDateTime }
	 *
	 */
	public void setDateDebut(LocalDateTime value) {
		this.dateDebut = value;
	}

}
