//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package fr.progilone.pgcn.domain.jaxb.aip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Métadonnées de gestion du document
 *
 * <p>
 * Java class for DocMetaType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class.
 *
 * <pre>
 * &lt;complexType name="DocMetaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}authenticite" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}dateArchivage"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}dureeConservation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}identifiantDocPac"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}identifiantDocProducteur"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}docRelation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}evaluation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}communicabilite" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}noteDocument" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}serviceVersant"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}planClassement" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}identifiantVersement" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}projet" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}sortFinal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}structureDocument" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}version" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}versionPrecedente" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocMetaType",
		propOrder = { "authenticite", "dateArchivage", "dureeConservation", "identifiantDocPac",
				"identifiantDocProducteur", "docRelation", "evaluation", "communicabilite", "noteDocument",
				"serviceVersant", "planClassement", "identifiantVersement", "projet", "sortFinal", "structureDocument",
				"version", "versionPrecedente" })
public class DocMetaType {

	protected String authenticite;

	@XmlElement(required = true)
	protected String dateArchivage;

	protected Duration dureeConservation;

	@XmlElement(required = true)
	protected String identifiantDocPac;

	@XmlElement(required = true)
	protected String identifiantDocProducteur;

	protected List<DocRelationType> docRelation;

	protected EvaluationType evaluation;

	protected CommunicabiliteType communicabilite;

	protected StringNotNULLtext noteDocument;

	@XmlElement(required = true)
	protected String serviceVersant;

	protected StringNotNULLtext planClassement;

	protected String identifiantVersement;

	protected String projet;

	protected StringNotNULLtext sortFinal;

	protected List<String> structureDocument;

	protected String version;

	protected String versionPrecedente;

	/**
	 * Gets the value of the authenticite property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getAuthenticite() {
		return authenticite;
	}

	/**
	 * Sets the value of the authenticite property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAuthenticite(String value) {
		this.authenticite = value;
	}

	/**
	 * Gets the value of the dateArchivage property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getDateArchivage() {
		return dateArchivage;
	}

	/**
	 * Sets the value of the dateArchivage property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDateArchivage(String value) {
		this.dateArchivage = value;
	}

	/**
	 * Gets the value of the dureeConservation property.
	 * @return possible object is {@link Duration }
	 *
	 */
	public Duration getDureeConservation() {
		return dureeConservation;
	}

	/**
	 * Sets the value of the dureeConservation property.
	 * @param value allowed object is {@link Duration }
	 *
	 */
	public void setDureeConservation(Duration value) {
		this.dureeConservation = value;
	}

	/**
	 * Gets the value of the identifiantDocPac property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getIdentifiantDocPac() {
		return identifiantDocPac;
	}

	/**
	 * Sets the value of the identifiantDocPac property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setIdentifiantDocPac(String value) {
		this.identifiantDocPac = value;
	}

	/**
	 * Gets the value of the identifiantDocProducteur property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getIdentifiantDocProducteur() {
		return identifiantDocProducteur;
	}

	/**
	 * Sets the value of the identifiantDocProducteur property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setIdentifiantDocProducteur(String value) {
		this.identifiantDocProducteur = value;
	}

	/**
	 * Gets the value of the docRelation property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present inside the
	 * Jakarta XML Binding object. This is why there is not a <CODE>set</CODE> method for
	 * the docRelation property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows: <pre>
	 *    getDocRelation().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link DocRelationType }
	 *
	 *
	 */
	public List<DocRelationType> getDocRelation() {
		if (docRelation == null) {
			docRelation = new ArrayList<DocRelationType>();
		}
		return this.docRelation;
	}

	/**
	 * Gets the value of the evaluation property.
	 * @return possible object is {@link EvaluationType }
	 *
	 */
	public EvaluationType getEvaluation() {
		return evaluation;
	}

	/**
	 * Sets the value of the evaluation property.
	 * @param value allowed object is {@link EvaluationType }
	 *
	 */
	public void setEvaluation(EvaluationType value) {
		this.evaluation = value;
	}

	/**
	 * Gets the value of the communicabilite property.
	 * @return possible object is {@link CommunicabiliteType }
	 *
	 */
	public CommunicabiliteType getCommunicabilite() {
		return communicabilite;
	}

	/**
	 * Sets the value of the communicabilite property.
	 * @param value allowed object is {@link CommunicabiliteType }
	 *
	 */
	public void setCommunicabilite(CommunicabiliteType value) {
		this.communicabilite = value;
	}

	/**
	 * Gets the value of the noteDocument property.
	 * @return possible object is {@link StringNotNULLtext }
	 *
	 */
	public StringNotNULLtext getNoteDocument() {
		return noteDocument;
	}

	/**
	 * Sets the value of the noteDocument property.
	 * @param value allowed object is {@link StringNotNULLtext }
	 *
	 */
	public void setNoteDocument(StringNotNULLtext value) {
		this.noteDocument = value;
	}

	/**
	 * Gets the value of the serviceVersant property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getServiceVersant() {
		return serviceVersant;
	}

	/**
	 * Sets the value of the serviceVersant property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setServiceVersant(String value) {
		this.serviceVersant = value;
	}

	/**
	 * Gets the value of the planClassement property.
	 * @return possible object is {@link StringNotNULLtext }
	 *
	 */
	public StringNotNULLtext getPlanClassement() {
		return planClassement;
	}

	/**
	 * Sets the value of the planClassement property.
	 * @param value allowed object is {@link StringNotNULLtext }
	 *
	 */
	public void setPlanClassement(StringNotNULLtext value) {
		this.planClassement = value;
	}

	/**
	 * Gets the value of the identifiantVersement property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getIdentifiantVersement() {
		return identifiantVersement;
	}

	/**
	 * Sets the value of the identifiantVersement property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setIdentifiantVersement(String value) {
		this.identifiantVersement = value;
	}

	/**
	 * Gets the value of the projet property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getProjet() {
		return projet;
	}

	/**
	 * Sets the value of the projet property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setProjet(String value) {
		this.projet = value;
	}

	/**
	 * Gets the value of the sortFinal property.
	 * @return possible object is {@link StringNotNULLtext }
	 *
	 */
	public StringNotNULLtext getSortFinal() {
		return sortFinal;
	}

	/**
	 * Sets the value of the sortFinal property.
	 * @param value allowed object is {@link StringNotNULLtext }
	 *
	 */
	public void setSortFinal(StringNotNULLtext value) {
		this.sortFinal = value;
	}

	/**
	 * Gets the value of the structureDocument property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present inside the
	 * Jakarta XML Binding object. This is why there is not a <CODE>set</CODE> method for
	 * the structureDocument property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows: <pre>
	 *    getStructureDocument().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 *
	 *
	 */
	public List<String> getStructureDocument() {
		if (structureDocument == null) {
			structureDocument = new ArrayList<String>();
		}
		return this.structureDocument;
	}

	/**
	 * Gets the value of the version property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the versionPrecedente property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getVersionPrecedente() {
		return versionPrecedente;
	}

	/**
	 * Sets the value of the versionPrecedente property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setVersionPrecedente(String value) {
		this.versionPrecedente = value;
	}

}
