//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package org.numahop.numahop.domain.jaxb.aip;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 *
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;description xmlns:ISO-639-3="urn:un:unece:uncefact:codelist:draft:DAF:languageCode:2011-10-07" xmlns:RA="urn:un:unece:uncefact:codelist:draft:DAF:accessRestrictionCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;caractérise des relations entre les documents&lt;/description&gt;
 * </pre>
 *
 *
 *
 * <p>
 * Java class for docRelationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class.
 *
 * <pre>
 * &lt;complexType name="docRelationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}typeRelation"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}sourceRelation"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/aip}identifiantSourceRelation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "docRelationType", propOrder = { "typeRelation", "sourceRelation", "identifiantSourceRelation" })
public class DocRelationType {

	@XmlElement(required = true)
	protected String typeRelation;

	@XmlElement(required = true)
	protected String sourceRelation;

	@XmlElement(required = true)
	protected String identifiantSourceRelation;

	/**
	 * Gets the value of the typeRelation property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getTypeRelation() {
		return typeRelation;
	}

	/**
	 * Sets the value of the typeRelation property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setTypeRelation(String value) {
		this.typeRelation = value;
	}

	/**
	 * Gets the value of the sourceRelation property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getSourceRelation() {
		return sourceRelation;
	}

	/**
	 * Sets the value of the sourceRelation property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSourceRelation(String value) {
		this.sourceRelation = value;
	}

	/**
	 * Gets the value of the identifiantSourceRelation property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getIdentifiantSourceRelation() {
		return identifiantSourceRelation;
	}

	/**
	 * Sets the value of the identifiantSourceRelation property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setIdentifiantSourceRelation(String value) {
		this.identifiantSourceRelation = value;
	}

}
