//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package org.numahop.numahop.domain.jaxb.aip;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for empreinteType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class.
 *
 * <pre>
 * &lt;complexType name="empreinteType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.cines.fr/pac/aip&gt;stringNotNULL"&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="MD5"/&gt;
 *             &lt;enumeration value="SHA-1"/&gt;
 *             &lt;enumeration value="SHA-256"/&gt;
 *             &lt;enumeration value="SHA-512"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "empreinteType", propOrder = { "value" })
public class EmpreinteType {

	@XmlValue
	protected String value;

	@XmlAttribute(name = "type", required = true)
	protected String type;

	/**
	 * Chaine de caractères composée d'au moins 1 caractère imprimable ou non
	 * exclusivement composé d'espace et/ou de tabulations et/ou de nouvelle ligne et/ou
	 * de retour chariot
	 * @return possible object is {@link String }
	 *
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the type property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setType(String value) {
		this.type = value;
	}

}
