//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.cines.fr/pac/aip",
		elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
@XmlJavaTypeAdapter(value = LocalDateTimeXmlAdapter.class, type = LocalDateTime.class)
package org.numahop.numahop.domain.jaxb.aip;

import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.numahop.numahop.domain.jaxb.adapters.LocalDateTimeXmlAdapter;
import java.time.LocalDateTime;
