//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package org.numahop.numahop.domain.jaxb.aip;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for traitementType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this
 * class.
 *
 * <pre>
 * &lt;complexType name="traitementType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.cines.fr/pac/aip&gt;traitementEnum"&gt;
 *       &lt;attribute name="language" use="required" type="{urn:un:unece:uncefact:codelist:draft:DAF:languageCode:2011-10-07}LanguageCodeType" fixed="fra" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "traitementType", propOrder = { "value" })
public class TraitementType {

	@XmlValue
	protected TraitementEnum value;

	@XmlAttribute(name = "language", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String language;

	/**
	 * Gets the value of the value property.
	 * @return possible object is {@link TraitementEnum }
	 *
	 */
	public TraitementEnum getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * @param value allowed object is {@link TraitementEnum }
	 *
	 */
	public void setValue(TraitementEnum value) {
		this.value = value;
	}

	/**
	 * Gets the value of the language property.
	 * @return possible object is {@link String }
	 *
	 */
	public String getLanguage() {
		if (language == null) {
			return "fra";
		}
		else {
			return language;
		}
	}

	/**
	 * Sets the value of the language property.
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setLanguage(String value) {
		this.language = value;
	}

}
