//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//

package org.numahop.numahop.domain.jaxb.avis;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.time.LocalDateTime;

/**
 * This object contains factory methods for each Java content interface and Java element
 * interface generated in the fr.cines.pac.avis package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of
 * schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these
 * are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _PacAvis_QNAME = new QName("http://www.cines.fr/pac/avis", "pac_avis");

	private final static QName _Serveur_QNAME = new QName("http://www.cines.fr/pac/avis", "serveur");

	private final static QName _Id_QNAME = new QName("http://www.cines.fr/pac/avis", "id");

	private final static QName _IdVersement_QNAME = new QName("http://www.cines.fr/pac/avis", "id_versement");

	private final static QName _IdDemande_QNAME = new QName("http://www.cines.fr/pac/avis", "id_demande");

	private final static QName _Commentaire_QNAME = new QName("http://www.cines.fr/pac/avis", "commentaire");

	private final static QName _ErreurValidation_QNAME = new QName("http://www.cines.fr/pac/avis", "erreurValidation");

	private final static QName _Contrles_QNAME = new QName("http://www.cines.fr/pac/avis", "contrles");

	private final static QName _Title_QNAME = new QName("http://www.cines.fr/pac/avis", "title");

	private final static QName _DateArchivage_QNAME = new QName("http://www.cines.fr/pac/avis", "dateArchivage");

	private final static QName _DateDemande_QNAME = new QName("http://www.cines.fr/pac/avis", "dateDemande");

	private final static QName _DateCommunication_QNAME = new QName("http://www.cines.fr/pac/avis",
			"dateCommunication");

	private final static QName _IdentifiantDocPac_QNAME = new QName("http://www.cines.fr/pac/avis",
			"identifiantDocPac");

	private final static QName _IdentifiantDocProducteur_QNAME = new QName("http://www.cines.fr/pac/avis",
			"identifiantDocProducteur");

	private final static QName _CodeErreur_QNAME = new QName("http://www.cines.fr/pac/avis", "codeErreur");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: fr.cines.pac.avis
	 *
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link PacAvisType }
	 *
	 */
	public PacAvisType createPacAvisType() {
		return new PacAvisType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PacAvisType }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link PacAvisType
	 * }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "pac_avis")
	public JAXBElement<PacAvisType> createPacAvis(PacAvisType value) {
		return new JAXBElement<PacAvisType>(_PacAvis_QNAME, PacAvisType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "serveur")
	public JAXBElement<String> createServeur(String value) {
		return new JAXBElement<String>(_Serveur_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "id")
	public JAXBElement<String> createId(String value) {
		return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "id_versement")
	public JAXBElement<String> createIdVersement(String value) {
		return new JAXBElement<String>(_IdVersement_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "id_demande")
	public JAXBElement<String> createIdDemande(String value) {
		return new JAXBElement<String>(_IdDemande_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "commentaire")
	public JAXBElement<String> createCommentaire(String value) {
		return new JAXBElement<String>(_Commentaire_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "erreurValidation")
	public JAXBElement<String> createErreurValidation(String value) {
		return new JAXBElement<String>(_ErreurValidation_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "contrles")
	public JAXBElement<String> createContrles(String value) {
		return new JAXBElement<String>(_Contrles_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "title")
	public JAXBElement<String> createTitle(String value) {
		return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar
	 * }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 * }{@code <}{@link XMLGregorianCalendar }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "dateArchivage")
	public JAXBElement<LocalDateTime> createDateArchivage(LocalDateTime value) {
		return new JAXBElement<LocalDateTime>(_DateArchivage_QNAME, LocalDateTime.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar
	 * }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 * }{@code <}{@link XMLGregorianCalendar }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "dateDemande")
	public JAXBElement<LocalDateTime> createDateDemande(LocalDateTime value) {
		return new JAXBElement<LocalDateTime>(_DateDemande_QNAME, LocalDateTime.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar
	 * }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement
	 * }{@code <}{@link XMLGregorianCalendar }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "dateCommunication")
	public JAXBElement<LocalDateTime> createDateCommunication(LocalDateTime value) {
		return new JAXBElement<LocalDateTime>(_DateCommunication_QNAME, LocalDateTime.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "identifiantDocPac")
	public JAXBElement<String> createIdentifiantDocPac(String value) {
		return new JAXBElement<String>(_IdentifiantDocPac_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "identifiantDocProducteur")
	public JAXBElement<String> createIdentifiantDocProducteur(String value) {
		return new JAXBElement<String>(_IdentifiantDocProducteur_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.cines.fr/pac/avis", name = "codeErreur")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createCodeErreur(String value) {
		return new JAXBElement<String>(_CodeErreur_QNAME, String.class, null, value);
	}

}
