//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.16 at 03:45:09 PM CEST
//


package fr.progilone.pgcn.domain.jaxb.avis;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.time.LocalDateTime;


/**
 * <p>Java class for pac_avisType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="pac_avisType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}serveur"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}id" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}id_versement" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}id_demande" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}title" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}dateArchivage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}dateDemande" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}dateCommunication" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}identifiantDocPac" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}identifiantDocProducteur" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}codeErreur" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}commentaire"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}erreurValidation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cines.fr/pac/avis}contrles" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pac_avisType", propOrder = {
    "serveur",
    "id",
    "idVersement",
    "idDemande",
    "title",
    "dateArchivage",
    "dateDemande",
    "dateCommunication",
    "identifiantDocPac",
    "identifiantDocProducteur",
    "codeErreur",
    "commentaire",
    "erreurValidation",
    "contrles"
})
public class PacAvisType {

    @XmlElement(required = true)
    protected String serveur;
    protected String id;
    @XmlElement(name = "id_versement")
    protected String idVersement;
    @XmlElement(name = "id_demande")
    protected String idDemande;
    protected List<String> title;
    @XmlSchemaType(name = "dateTime")
    protected LocalDateTime dateArchivage;
    @XmlSchemaType(name = "dateTime")
    protected LocalDateTime dateDemande;
    @XmlSchemaType(name = "dateTime")
    protected LocalDateTime dateCommunication;
    protected String identifiantDocPac;
    protected String identifiantDocProducteur;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String codeErreur;
    @XmlElement(required = true)
    protected String commentaire;
    protected String erreurValidation;
    protected String contrles;

    /**
     * Gets the value of the serveur property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getServeur() {
        return serveur;
    }

    /**
     * Sets the value of the serveur property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setServeur(String value) {
        this.serveur = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idVersement property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdVersement() {
        return idVersement;
    }

    /**
     * Sets the value of the idVersement property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdVersement(String value) {
        this.idVersement = value;
    }

    /**
     * Gets the value of the idDemande property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdDemande() {
        return idDemande;
    }

    /**
     * Sets the value of the idDemande property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdDemande(String value) {
        this.idDemande = value;
    }

    /**
     * Gets the value of the title property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getTitle() {
        if (title == null) {
            title = new ArrayList<String>();
        }
        return this.title;
    }

    /**
     * Gets the value of the dateArchivage property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public LocalDateTime getDateArchivage() {
        return dateArchivage;
    }

    /**
     * Sets the value of the dateArchivage property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateArchivage(LocalDateTime value) {
        this.dateArchivage = value;
    }

    /**
     * Gets the value of the dateDemande property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public LocalDateTime getDateDemande() {
        return dateDemande;
    }

    /**
     * Sets the value of the dateDemande property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateDemande(LocalDateTime value) {
        this.dateDemande = value;
    }

    /**
     * Gets the value of the dateCommunication property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public LocalDateTime getDateCommunication() {
        return dateCommunication;
    }

    /**
     * Sets the value of the dateCommunication property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateCommunication(LocalDateTime value) {
        this.dateCommunication = value;
    }

    /**
     * Gets the value of the identifiantDocPac property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentifiantDocPac() {
        return identifiantDocPac;
    }

    /**
     * Sets the value of the identifiantDocPac property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentifiantDocPac(String value) {
        this.identifiantDocPac = value;
    }

    /**
     * Gets the value of the identifiantDocProducteur property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentifiantDocProducteur() {
        return identifiantDocProducteur;
    }

    /**
     * Sets the value of the identifiantDocProducteur property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentifiantDocProducteur(String value) {
        this.identifiantDocProducteur = value;
    }

    /**
     * Gets the value of the codeErreur property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodeErreur() {
        return codeErreur;
    }

    /**
     * Sets the value of the codeErreur property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodeErreur(String value) {
        this.codeErreur = value;
    }

    /**
     * Gets the value of the commentaire property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommentaire() {
        return commentaire;
    }

    /**
     * Sets the value of the commentaire property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommentaire(String value) {
        this.commentaire = value;
    }

    /**
     * Gets the value of the erreurValidation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErreurValidation() {
        return erreurValidation;
    }

    /**
     * Sets the value of the erreurValidation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErreurValidation(String value) {
        this.erreurValidation = value;
    }

    /**
     * Gets the value of the contrles property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContrles() {
        return contrles;
    }

    /**
     * Sets the value of the contrles property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContrles(String value) {
        this.contrles = value;
    }

}
